datasets:
  legal_data:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/paper_workloads/corporate_lobbying/legal.json"

default_model: gpt-4o-mini

operations:
  assess_bill_relevance:
    type: map
    output:
      schema:
        is_relevant: "bool"
        explanation: "str"
    prompt: |
      Analyze the following bill and company information:

      Bill Title: {{ input.bill_title }}
      Bill Summary: {{ input.bill_summary }}
      Company Name: {{ input.company_name }}
      Company Description: {{ input.company_description }}

      Determine whether this bill is relevant for the company. To do this:
      1. Identify the legal consequences of the bill.
      2. Assess whether those consequences are relevant to the company's business model, structure, or activities.

      Provide your assessment as a boolean (true/false) for relevance and a brief explanation.
    validate:
      - "isinstance(output['is_relevant'], bool)"
      - "len(output['explanation']) > 0"

pipeline:
  steps:
    - name: relevance_assessment
      input: legal_data
      operations:
        - assess_bill_relevance

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/paper_workloads/corporate_lobbying/relevance_assessment_baseline.json"
