datasets:
  biodex_sample:
    type: file
    path: /Users/shreyashankar/Documents/hacking/motion-v3/paper_workloads/biodex/biodex_sample.json
  biodex_terms:
    type: file
    path: /Users/shreyashankar/Documents/hacking/motion-v3/paper_workloads/biodex/biodex_terms.json

default_model: gpt-4o-mini

operations:
  match_reactions:
    type: equijoin
    embedding_model: text-embedding-3-small
    limit_comparisons: 100000
    comparison_prompt: |
      {% set reaction_lower = right.reaction | lower | replace(',', ' ') | replace('.', ' ') %}
      {% set fulltext_lower = left.fulltext_processed | lower %}
      {% set total_words = reaction_lower | wordcount %}
      {% set current_word = '' %}
      {% set words_found = [] %}
      {% for char in reaction_lower %}
        {% if char == ' ' %}
          {% if current_word and current_word in fulltext_lower %}
            {% set words_found = words_found + [current_word] %}
          {% endif %}
          {% set current_word = '' %}
        {% else %}
          {% set current_word = current_word + char %}
        {% endif %}
      {% endfor %}
      {% if current_word and current_word in fulltext_lower %}
        {% set words_found = words_found + [current_word] %}
      {% endif %}
      {% set match_percentage = (words_found | length / total_words * 100) | round(2) %}

      Can the following condition be found in the following medical article?
      Medical article: {{ left.fulltext_processed }}

      Condition we are looking for: {{ right.reaction }}

      Analysis of condition words in the article:
      - Words found: {{ words_found | join(', ') or 'None' }}
      - Words not found: {{ words_not_found | join(', ') or 'None' }}
      - Percentage of words found: {{ match_percentage }}%

      Note that the presence of a condition is not solely determined by the presence of its individual words. You should consider the context and semantic meaning of the words in the article.

      Determine if {{ right.reaction }} is described in the medical article, considering the context and meaning beyond just the presence of individual words.

  group_reactions:
    type: reduce
    reduce_key:
      - id
    prompt: |
      Given the following medical article, rank the following conditions in order of most confident to least confident that the article is describing the condition:
      {{ values[0].fulltext_processed }}

      Conditions: {% for value in values %}{{ value.reaction }}{% if not loop.last %}, {% endif %}{% endfor %}

      There may be conditions described in the article that are not in the list. Do not include them in the ranked list. Only focus on the conditions in the list.
    optimize: false
    output:
      schema:
        ranked_conditions: list[string]
    pass_through: true

optimizer_config:
  sample_sizes:
    equijoin: 500
  equijoin:
    target_recall: 0.75
    estimated_selectivity: 0.004

pipeline:
  steps:
    - name: match_reactions
      operations:
        - match_reactions:
            left: biodex_sample
            right: biodex_terms

    - name: group_reactions
      input: match_reactions
      operations:
        - group_reactions

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/paper_workloads/biodex/extracted_reactions_pipeline.json"
