name: medical_record_join

datasets:
  meds:
    type: file
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/meds.json
  transcripts:
    type: file
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/unnestd_and_deduped_meds.json

default_model: gpt-4o-mini

operations:
  join_meds_transcripts:
    type: equijoin
    join_key:
      left:
        name: medicine
      right:
        name: medication
    comparison_prompt: |
      Compare the following medication names:
      {{ left.medicine }}
      {{ right.medication }}

      Determine if these entries refer to the same medication. Consider the following:
      1. Do the medication names match exactly?
      2. Are there any minor spelling differences or abbreviations?
      3. Could any differences be due to brand name vs. generic name?

      Respond with true if you believe these entries match, or false if they do not.

pipeline:
  steps:
    - name: join_meds_transcripts
      operations:
        - join_meds_transcripts:
            left: meds
            right: transcripts

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/joined_meds_transcripts.json"
