datasets:
  transcripts:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json"

default_model: gpt-4o-mini

operations:
  extract_medical_info:
    type: filter
    output:
      schema:
        references_pain_reliever: "bool"
    prompt: |
      Analyze the following transcript of a conversation between a doctor and a patient:

      {{ input.src }}

      Determine if the transcript references a pain reliever medication.

pipeline:
  steps:
    - name: medical_info_extraction
      input: transcripts
      operations:
        - extract_medical_info

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/pain_reliever_references.json"
