datasets:
  transcripts:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json"

default_model: gpt-4o-mini

operations:
  extract_medical_info:
    type: map
    output:
      schema:
        medication_info: "str"
    prompt: |
      Analyze the following transcript of a conversation between a doctor and a patient:

      {{ input.src }}

      Extract and list all medications, dosages, and symptoms mentioned in the transcript.
      Begin your medication_info output with "Medication Info: "
      If a piece of information is not found, return an empty string.
    validate:
      - "output['medication_info'].startswith('Medication Info: ')"
    num_retries_on_validate_failure: 1

    # gleaning:
    #   num_rounds: 1
    #   validation_prompt: |
    #     Review the original transcript and the extracted information:

    #     Extracted: {{ output }}

    #     Evaluate the extraction for completeness and accuracy:
    #     1. Are all medications, dosages, and symptoms from the transcript included?
    #     2. Is the extracted information correct and relevant?

pipeline:
  steps:
    - name: medical_info_extraction
      input: transcripts
      operations:
        - extract_medical_info

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/extracted_medical_info.json"
