datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  split_extract_medical_info:
    chunk_size: 663
    peripheral_chunks:
      next:
        head:
          count: 1
      previous:
        tail:
          count: 1
    split_key: src
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    prompt: "Analyze the following segment of the transcript:\n\n{{ input.chunk_content\
      \ }}\n\nExtract and list all medications, dosages, and symptoms mentioned in\
      \ this segment.\nIf a piece of information is not found, return an empty list\
      \ for that category.\n\nProvide your response in the following JSON format:\n\
      {\n  \"medications\": [\"medication1\", \"medication2\", ...],\n  \"dosages\"\
      : [\"dosage1\", \"dosage2\", ...],\n  \"symptoms\": [\"symptom1\", \"symptom2\"\
      , ...]\n}\n Only process the main chunk."
    type: map
  subreduce_extract_medical_info:
    commutative: true
    input:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    pass_through: true
    prompt: "Combine the information extracted from the chunks below to provide a\
      \ comprehensive list of medications, dosages, and symptoms from the conversation\
      \ transcript.\n\nEach chunk contains dictionaries with the keys 'medications',\
      \ 'dosages', and 'symptoms'. Use this information to generate a single consolidated\
      \ response.\n\nFinal Format:\n{\n  \"medications\": [...],\n  \"dosages\": [...],\n\
      \  \"symptoms\": [...]\n}\n\nChunks to combine:\n{{ values }}"
    reduce_key: document_id
    type: reduce
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
