datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medical_info:
    gleaning:
      num_rounds: 1
      validation_prompt: '1. Does the output accurately capture all medications, dosages,
        and symptoms mentioned in the provided transcript?

        2. Are there any relevant instances of medications, dosages, or symptoms in
        the transcript that were not included in the output?

        3. Is the information in the output presented in a consistent and correct
        format as specified in the task description?

        4. Are there any discrepancies or inaccuracies in the extracted information
        compared to the transcript?

        5. Could the quality of the output be enhanced by a more thorough analysis
        of the input text?'
    output:
      schema:
        medications: 'list[{medication: str, dosage: str, symptom: str}]'
    prompt: 'Analyze the following transcript of a conversation between a doctor and
      a patient:


      {{ input.src }}


      Extract and list all medications, dosages, and symptoms mentioned in the transcript.

      If a piece of information is not found, return an empty list for that category.

      '
    type: map
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - extract_medical_info
