datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medical_info_parallel_map:
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    prompts:
      - name: Extract Medications
        output_keys:
          - medications
        prompt:
          "Analyze the following transcript of a conversation between a doctor
          and a patient:


          {{ input.src }}


          Extract and list all medications mentioned in the transcript. If no medications
          are found, return an empty list.

          "
      - name: Extract Dosages
        output_keys:
          - dosages
        prompt:
          "Analyze the following transcript of a conversation between a doctor
          and a patient:


          {{ input.src }}


          Extract and list all dosages mentioned in the transcript. If no dosages are
          found, return an empty list.

          "
      - name: Extract Symptoms
        output_keys:
          - symptoms
        prompt:
          "Analyze the following transcript of a conversation between a doctor
          and a patient:


          {{ input.src }}


          Extract and list all symptoms mentioned in the transcript. If no symptoms
          are found, return an empty list.

          "
    type: parallel_map
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
    - input: transcripts
      name: medical_info_extraction
      operations:
        - extract_medical_info_parallel_map
