datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medical_info:
    output:
      schema:
        medications: 'list[{medication: str, dosage: str, symptom: str}]'
    prompt: "Analyze the following transcript of a conversation between a doctor and\
      \ a patient:\n\n{{ input.src }}\n\nExtract and list all the medications mentioned\
      \ along with their dosages if provided. Also list any symptoms mentioned in\
      \ the conversation, associating these with specific medications if applicable.\
      \ For example, link medications like 'Epipen' with symptoms such as 'anaphylaxis.'\
      \ Ensure that each category\u2014medications, dosages, and symptoms\u2014is\
      \ included in the output as a list, even if some remain empty."
    type: map
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - extract_medical_info
