datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  split_extract_medical_info:
    chunk_group_id_field: extract_medical_info_chunk_group_id
    chunk_size: 1086
    peripheral_chunks:
      previous:
        tail:
          count: 1
    split_key: src
    summary_model: gpt-4o-mini
    summary_prompt: 'Summarize the following chunk: {{ chunk_content }}


      Focus on identifying any mentioned medications, their dosages, and symptoms
      experienced or monitored.'
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        medication_info: str
    prompt: 'Extract and list all medications, dosages, and symptoms mentioned in
      the following text:


      {{ input.chunk_content }}


      If a piece of information is not found, return an empty string. Only process
      the main chunk.'
    type: map
  subreduce_extract_medical_info:
    commutative: true
    input:
      schema:
        medication_info: str
    model: gpt-4o-mini
    output:
      schema:
        medication_info: str
    pass_through: true
    prompt: 'Combine the following extracted information from different chunks to
      provide a comprehensive list of all medications, dosages, and symptoms mentioned
      in the conversation transcript:


      {% for value in values %}

      {{ value.medication_info }}

      {% endfor %}'
    reduce_key:
    - extract_medical_info_chunk_group_id
    type: reduce
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
