datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  split_extract_medical_info:
    chunk_size: 541
    peripheral_chunks:
      previous:
        head:
          count: 2
        tail:
          count: 1.5
    split_key: src
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    prompt: "Extract and list all medications, dosages, and symptoms mentioned in\
      \ the following chunk of a medical conversation transcript:\n\n{{ input.chunk_content\
      \ }}\n\nIf a piece of information is not found, return an empty list for that\
      \ category.\n\nProvide your response in the following JSON format:\n{\n  \"\
      medications\": [\"medication1\", \"medication2\", ...],\n  \"dosages\": [\"\
      dosage1\", \"dosage2\", ...],\n  \"symptoms\": [\"symptom1\", \"symptom2\",\
      \ ...]\n} Only process the main chunk."
    type: map
  subreduce_extract_medical_info:
    input:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    pass_through: true
    prompt: "Combine the following chunks of extracted information from a conversation\
      \ transcript into a single, comprehensive list:\n\n{{ values }}\n\nMerge all\
      \ medications, dosages, and symptoms mentioned into their respective categories.\n\
      \nProvide your response in the following JSON format:\n{\n  \"medications\"\
      : [\"medication1\", \"medication2\", ...],\n  \"dosages\": [\"dosage1\", \"\
      dosage2\", ...],\n  \"symptoms\": [\"symptom1\", \"symptom2\", ...]\n}"
    reduce_key: document_id
    type: reduce
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
