datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medical_info:
    num_retries_on_validate_failure: 1
    output:
      schema:
        medication_info: str
    prompt: 'Analyze the following transcript of a conversation between a doctor and
      a patient:


      {{ input.src }}


      Extract and list all medications, dosages, and symptoms mentioned in the transcript.

      Begin your medication_info output with "Medication Info: "

      If a piece of information is not found, return an empty string.

      '
    recursively_optimize: false
    type: map
    validate:
    - 'output[''medication_info''].startswith(''Medication Info: '')'
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - extract_medical_info
