datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  split_extract_medical_info:
    chunk_size: 813
    split_key: src
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    prompt: "Extract the information from the following portion of the transcript:\n\
      \n{{ input.chunk_content }}\n\nList all medications, dosages, and symptoms mentioned.\
      \ If a piece of information is not found, return an empty list for that category\
      \ in JSON format:\n{\n  \"medications\": [\"medication1\", \"medication2\",\
      \ ...],\n  \"dosages\": [\"dosage1\", \"dosage2\", ...],\n  \"symptoms\": [\"\
      symptom1\", \"symptom2\", ...]\n} Only process the main chunk."
    type: map
  subreduce_extract_medical_info:
    input:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    pass_through: true
    prompt: "Collect all the extracted information about medications, dosages, and\
      \ symptoms from the following partial results:\n\n{{ values }}\n\nCombine them\
      \ into a single unified response in JSON format, as follows:\n{\n  \"medications\"\
      : [\"medication1\", \"medication2\", ...],\n  \"dosages\": [\"dosage1\", \"\
      dosage2\", ...],\n  \"symptoms\": [\"symptom1\", \"symptom2\", ...]\n}"
    reduce_key: document_id
    type: reduce
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
