datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medical_info:
    gleaning:
      num_rounds: 1
      validation_prompt: 'Please evaluate the output of the ''extract_medical_info''
        operation for the given transcript by answering the following questions:


        1. Completeness: Are there any medications, dosages, or symptoms mentioned
        in the transcript that were not included in the output? If so, please specify
        which pieces of information were missed.


        2. Accuracy: Is each extracted medication, dosage, and symptom accurately
        represented in the output? Note any discrepancies between the transcript and
        the extracted information.


        3. Precision: Would the output benefit from a more detailed analysis of the
        transcript? For example, are there nuances in symptom descriptions or medication
        instructions that are oversimplified or misunderstood in the extraction?


        4. Format Consistency: Is the output format consistent with the expected structure,
        with clear separation and labeling of medications, dosages, and symptoms?
        Identify any formatting issues or inconsistencies.


        5. Information Errors: Are there any errors or contradictions in the extracted
        data, such as incorrect dosages or symptom descriptions? Please highlight
        any such issues.


        Provide a summary of your assessment indicating overall performance and any
        recommended improvements.'
    output:
      schema:
        medication_info: str
    prompt: 'Analyze the following transcript of a conversation between a doctor and
      a patient:


      {{ input.src }}


      Extract and list all medications, dosages, and symptoms mentioned in the transcript.

      If a piece of information is not found, return an empty string.

      '
    type: map
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - extract_medical_info
