datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  gather_src_extract_medical_info:
    content_key: src_chunk
    doc_id_key: split_extract_medical_info_id
    order_key: split_extract_medical_info_chunk_num
    peripheral_chunks:
      next:
        head:
          count: 3
      previous:
        tail:
          count: 3
    type: gather
  split_extract_medical_info:
    chunk_size: 150
    split_key: src
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        medication_info: str
    prompt: 'Analyze the following transcript chunk of a conversation between a doctor
      and a patient:


      {{ input.src_chunk }}


      Extract and list all medications, dosages, and symptoms mentioned in the transcript.

      Begin your medication_info output with "Medication Info: " If a piece of information
      is not found, return an empty string. Only process the main chunk.'
    type: map
  subreduce_extract_medical_info:
    commutative: true
    input:
      schema:
        medication_info: str
    model: gpt-4o-mini
    output:
      schema:
        medication_info: str
    pass_through: true
    prompt: 'Combine the extracted information from multiple chunks as follows:


      {% for value in values %}

      {{ value.medication_info }}

      {% endfor %}


      Ensure all medications, dosages, and symptoms are listed comprehensively. Omit
      duplicate entries and present a consolidated summary starting with "Medication
      Info:". If a specific category of information is missing in all chunks, leave
      it out from the final summary but maintain the format integrity.'
    reduce_key:
    - split_extract_medical_info_id
    type: reduce
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - gather_src_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
