datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  split_extract_medical_info:
    chunk_size: 681
    peripheral_chunks:
      next:
        head:
          count: 1
      previous:
        tail:
          count: 1
    split_key: src
    type: split
  submap_extract_medical_info:
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    prompt: "Extract and list all medications, dosages, and symptoms mentioned in\
      \ the transcript chunk:\n\n{{ input.chunk_content }}\n\nIf a piece of information\
      \ is not found, return an empty list for that category. Provide your response\
      \ in the following JSON format:\n{\n  \"medications\": [\"medication1\", \"\
      medication2\", ...],\n  \"dosages\": [\"dosage1\", \"dosage2\", ...],\n  \"\
      symptoms\": [\"symptom1\", \"symptom2\", ...]\n} Only process the main chunk."
    type: map
  subreduce_extract_medical_info:
    input:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    model: gpt-4o-mini
    output:
      schema:
        dosages: list[str]
        medications: list[str]
        symptoms: list[str]
    pass_through: true
    prompt: "Combine the following extracted data from multiple conversation chunks\
      \ into a comprehensive list of mentioned details in the transcript.\n\n{% set\
      \ medications = [] %}\n{% set dosages = [] %}\n{% set symptoms = [] %}\n\n{%\
      \ for value in values %}\n  {% for med in value.medications %}\n    {% if med\
      \ not in medications %}\n      {{ medications.append(med) }}\n    {% endif %}\n\
      \  {% endfor %}\n  {% for dose in value.dosages %}\n    {% if dose not in dosages\
      \ %}\n      {{ dosages.append(dose) }}\n    {% endif %}\n  {% endfor %}\n  {%\
      \ for symptom in value.symptoms %}\n    {% if symptom not in symptoms %}\n \
      \     {{ symptoms.append(symptom) }}\n    {% endif %}\n  {% endfor %}\n{% endfor\
      \ %}\n\n{\n  \"medications\": {{ medications | sort }},\n  \"dosages\": {{ dosages\
      \ | sort }},\n  \"symptoms\": {{ symptoms | sort }}\n}"
    reduce_key: document_id
    type: reduce
pipeline:
  output:
    path: extracted_medical_info.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - split_extract_medical_info
    - submap_extract_medical_info
    - subreduce_extract_medical_info
