datasets:
  deduped_meds:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/unnestd_and_deduped_meds.json
    type: file
default_model: gpt-4o-mini
operations:
  summarize_medication_contexts:
    commutative: true
    fold_batch_size: 7
    fold_prompt: 'Combine the following additional doctor-patient transcripts where
      the medication "{{ reduce_key }}" is mentioned to enhance the summary of patient
      settings and experiences:


      {% for item in values %}

      Transcript {{ loop.index }}:

      {{ item.src }}


      ---

      {% endfor %}


      Update the current summary with these new transcripts. Include any new information
      about:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.


      Start with the existing summary:


      {{ output[''summary''] }}'
    input:
      schema:
        medication: str
        src: str
    merge_batch_size: 2
    merge_prompt: 'Merge the summaries of multiple folded outputs to create a cohesive
      overview of the settings in which the medication "{{ reduce_key }}" is used.
      This task aims to simulate a comprehensive analysis as if the original reduce
      prompt had processed all transcripts collectively from the start.


      You have the following summaries:


      {% for output in outputs %}

      Summary {{ loop.index }}:

      {{ output[''summary''] }}


      ---

      {% endfor %}


      Combine the information from these summaries. Ensure the consolidated summary
      captures:


      1. A cohesive summary of why patients take this medication.

      2. Comprehensive details on any side effects experienced or mentioned.

      3. A clear description of any interactions with other medications or treatments
      mentioned.


      Produce a unified final summary that integrates findings from all summaries
      provided, maintaining consistency and clarity of information.'
    output:
      schema:
        summary: str
    prompt: 'Analyze the following doctor-patient transcripts where the medication
      "{{ reduce_key }}" is mentioned:


      {% for item in values %}

      Transcript {{ loop.index }}:

      {{ item.src }}


      ---

      {% endfor %}


      Based on these doctor-patient transcripts, provide a summary of the settings
      in which patients take the medication "{{ reduce_key }}". Include the following
      information:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.

      '
    reduce_key:
    - medication
    type: reduce
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/medication_context_summaries.json
    type: file
  steps:
  - input: deduped_meds
    name: medication_context_summarization
    operations:
    - summarize_medication_contexts
