datasets:
  deduped_meds:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/exploded_and_deduped_meds.json
    type: file
default_model: gpt-4o-mini
operations:
  summarize_medication_contexts:
    fold_batch_size: 6
    fold_prompt: 'Analyze the following doctor-patient transcripts where the medication
      "{{ reduce_key }}" is mentioned:


      {% for item in values %}

      Transcript {{ loop.index }}:

      {{ item.src }}


      ---

      {% endfor %}


      Considering the current summary and the new transcripts, provide an updated
      summary of the settings in which patients take the medication "{{ reduce_key
      }}". Include the following information:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.


      Current Summary:

      "{{ output.summary }}"


      Updated Summary:'
    input:
      schema:
        medication: str
        src: str
    merge_batch_size: 2
    merge_prompt: 'Combine the summaries provided below, which are generated from
      analyzing doctor-patient transcripts where the medication "{{ reduce_key }}"
      is mentioned. The summaries may originate from different batches of transcripts
      that have been incrementally folded to maintain up-to-date information about
      the use of the medication.


      Your goal is to merge these summaries into a single, cohesive output as if the
      original reduce prompt was run on all inputs at once. Ensure that the final
      summary includes the most comprehensive and accurate information available.


      {% for output in outputs %}

      Summary from batch {{ loop.index }}:

      {{ output.summary }}


      ---

      {% endfor %}


      Based on these summaries, provide a final summary of the settings in which patients
      take the medication "{{ reduce_key }}". Ensure you include the following information:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.


      Final Summary:'
    output:
      schema:
        summary: str
    prompt: 'Analyze the following doctor-patient transcripts where the medication
      "{{ reduce_key }}" is mentioned:


      {% for item in values %}

      Transcript {{ loop.index }}:

      {{ item.src }}


      ---

      {% endfor %}


      Based on these doctor-patient transcripts, provide a summary of the settings
      in which patients take the medication "{{ reduce_key }}". Include the following
      information:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.

      '
    reduce_key: medication
    type: reduce
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/medication_context_summaries.json
    type: file
  steps:
  - input: deduped_meds
    name: medication_context_summarization
    operations:
    - summarize_medication_contexts
