datasets:
  deduped_meds:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/unnestd_and_deduped_meds.json
    type: file
default_model: gpt-4o-mini
operations:
  summarize_medication_contexts:
    commutative: true
    fold_batch_size: 15
    fold_prompt:
      'Summarize the settings in which patients take the medication "{{
      reduce_key }}" by combining the new information in the following doctor-patient
      transcripts with the current summary:


      Current Summary:

      {{ output.summary }}


      ---


      New Transcripts:

      {% for value in inputs %}

      Transcript {{ loop.index + 1 }}:

      {{ value.src }}


      ---

      {% endfor %}


      Based on the new transcripts, update the summary to include any additional reasons
      for taking the medication "{{ reduce_key }}", side effects mentioned, or interactions
      with other medications or treatments. Ensure the updated summary merges seamlessly
      with the current information and clearly reflects any additional insights gathered
      from the new set of transcripts.'
    input:
      schema:
        medication: str
        src: str
    merge_batch_size: 2
    merge_prompt:
      'Combine the summaries produced by the previous fold operations
      into a comprehensive summary. These fold outputs are based on separate analyses
      of doctor-patient transcripts where the medication "{{ reduce_key }}" is mentioned.
      The goal is to merge these summaries into one cohesive output.


      Folded Outputs to Merge:

      {% for output in outputs %}

      - Summary {{ loop.index + 1 }}: {{ output.summary }}

      {% endfor %}


      Create a unified summary by synthesizing the information from these folded outputs.
      Ensure that the combined summary covers all insights gathered, including any
      additional reasons for taking the medication "{{ reduce_key }}", new side effects,
      or interactions with other medications or treatments mentioned across all transcripts.
      The final summary should flow logically and encapsulate all essential findings
      in a clear and concise manner.'
    output:
      schema:
        summary: str
    prompt:
      'Analyze the following doctor-patient transcripts where the medication
      "{{ reduce_key }}" is mentioned:


      {% for item in inputs %}

      Transcript {{ loop.index }}:

      {{ item.src }}


      ---

      {% endfor %}


      Based on these doctor-patient transcripts, provide a summary of the settings
      in which patients take the medication "{{ reduce_key }}". Include the following
      information:


      1. A brief summary of why a patient takes this medication.

      2. Any side effects experienced or mentioned.

      3. Any interactions with other medications or treatments mentioned.

      '
    reduce_key:
      - medication
    type: reduce
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/medication_context_summaries.json
    type: file
  steps:
    - input: deduped_meds
      name: medication_context_summarization
      operations:
        - summarize_medication_contexts
