datasets:
  deduped_meds:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/exploded_and_deduped_meds.json"

default_model: gpt-4o-mini

operations:
  summarize_medication_contexts:
    type: reduce
    reduce_key: medication
    input:
      schema:
        medication: str
        src: str
    output:
      schema:
        context_summary: str
    prompt: |
      Analyze the following doctor-patient transcripts where the medication "{{ reduce_key }}" is mentioned:

      {% for item in values %}
      Transcript {{ loop.index }}:
      {{ item.src }}

      ---
      {% endfor %}

      Based on these doctor-patient transcripts, provide a summary of the contexts in which patients take the medication "{{ reduce_key }}". Include the following information:

      1. A brief summary of why a patient takes this medication.
      2. Any side effects experienced or mentioned.
      3. Any interactions with other medications or treatments mentioned.

pipeline:
  steps:
    - name: medication_context_summarization
      input: deduped_meds
      operations:
        - summarize_medication_contexts

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/medication_context_summaries.json"
