datasets:
  transcripts:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json"

default_model: gpt-4o-mini

operations:
  extract_medications:
    optimize: false
    type: map
    output:
      schema:
        medication: list[str]
    prompt: |
      Analyze the following transcript of a conversation between a doctor and a patient:

      {{ input.src }}

      Extract and list all medications mentioned in the transcript.
      If no medications are mentioned, return an empty list.

  unnest_medications:
    type: unnest
    unnest_key: medication

  summarize_medications:
    type: reduce
    reduce_key: medication
    optimize: false
    output:
      schema:
        symptoms_summary: str
    prompt: |
      Analyze the following transcripts related to the medication "{{ reduce_key }}":

      {% for item in inputs %}
      Transcript {{ loop.index }}:
      {{ item.src }}
      {% endfor %}

      Based on these transcripts, provide a summary of the symptoms that the medication "{{ reduce_key }}" is typically used to treat or manage. If no specific symptoms are mentioned, provide a general description of the medication's common uses.

pipeline:
  steps:
    - name: medical_info_extraction
      input: transcripts
      operations:
        - extract_medications
        - unnest_medications
        - summarize_medications

  output:
    type: file
    path: "/Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/summarized_medical_info_synth.json"
