datasets:
  transcripts:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/raw_with_id.json
    type: file
default_model: gpt-4o-mini
operations:
  extract_medications:
    name: extract_medications
    optimize: false
    output:
      schema:
        medication: list[str]
    prompt: 'Analyze the following transcript of a conversation between a doctor and
      a patient:


      {{ input.src }}


      Extract and list all medications mentioned in the transcript.

      If no medications are mentioned, return an empty list.

      '
    type: map
  summarize_medications:
    name: summarize_medications
    optimize: false
    output:
      schema:
        symptoms_summary: str
    prompt: 'Analyze the following transcripts related to the medication "{{ reduce_key
      }}":


      {% for item in values %}

      Transcript {{ loop.index }}:

      {{ item.src }}

      {% endfor %}


      Based on these transcripts, provide a summary of the symptoms that the medication
      "{{ reduce_key }}" is typically used to treat or manage. If no specific symptoms
      are mentioned, provide a general description of the medication''s common uses.

      '
    reduce_key:
    - medication
    type: reduce
  synthesized_resolve_0:
    _intermediates:
      map_prompt: 'Analyze the following transcript of a conversation between a doctor
        and a patient:


        {{ input.src }}


        Extract and list all medications mentioned in the transcript.

        If no medications are mentioned, return an empty list.

        '
      reduce_key:
      - medication
    blocking_keys:
    - medication
    blocking_threshold: 0.7778
    comparison_model: gpt-4o-mini
    comparison_prompt: 'Compare the following two medications extracted from the conversation
      between a doctor and a patient:


      [Medication 1]:

      {{ input1.medication }}


      [Medication 2]:

      {{ input2.medication }}


      Are these medications likely referring to the same medication? Consider relevant
      attributes such as medication name, dosage form, strength, and any other contextual
      information that may indicate similarity. Respond with "True" if they are likely
      the same medication, or "False" if they are likely different medications.'
    embedding_model: text-embedding-3-small
    output:
      schema:
        medication: string
    resolution_model: gpt-4o-mini
    resolution_prompt: "Analyze the following duplicate medication entries:\n\n{%\
      \ for entry in matched_entries %}\nEntry {{ loop.index }}:\n{{ entry | tojson\
      \ }}\n\n{% endfor %}\n\nCreate a single, consolidated medication key that combines\
      \ the information from all duplicate entries. When merging, follow these guidelines:\n\
      1. If medication names appear in different formats or abbreviations, standardize\
      \ to the most widely accepted form. For example, convert trade names to generic\
      \ names where applicable.\n2. In cases of conflicting entries, prefer the most\
      \ complete medication name, including dosage and form if mentioned.\n3. Check\
      \ for consistency in spelling and correct any typographical errors detected\
      \ across entries.\n4. If the same medication has multiple mentions with varying\
      \ details, consolidate to the most detailed description available.\n\nEnsure\
      \ that the resultant merged key conforms to the following schema:\n{\n  \"medication\"\
      : \"string\"\n}\n\nReturn the consolidated key as a single string value."
    type: resolve
  unnest_medications:
    name: unnest_medications
    type: unnest
    unnest_key: medication
pipeline:
  output:
    path: /Users/shreyashankar/Documents/hacking/motion-v3/workloads/medical/summarized_medical_info_synth.json
    type: file
  steps:
  - input: transcripts
    name: medical_info_extraction
    operations:
    - extract_medications
    - unnest_medications
    - synthesized_resolve_0
    - summarize_medications
